services:
    # Services
    ## Stub service for IDE autocompletion; will be overridden in DaybreakStudiosAirbrakeExtension IF Airbrake is
    ## enabled.
    daybreak_studios_airbrake.service.airbrake:
        class: DaybreakStudios\Bundle\AirbrakeBundle\Services\DummyAirbrakeService

    # Listeners
    daybreak_studios_airbrake.listener.exception:
        class: DaybreakStudios\Bundle\AirbrakeBundle\Listener\ExceptionListener
        arguments:
            - @daybreak_studios_airbrake.service.airbrake
        tags:
            - name: kernel.event_listener
              event: kernel.exception
              method: onKernelException

    daybreak_studios_airbrake.listener.shutdown:
        class: DaybreakStudios\Bundle\AirbrakeBundle\Listener\ShutdownListener
        arguments:
            - @daybreak_studios_airbrake.service.airbrake
        tags:
            - name: kernel.event_listener
              event: kernel.controller
              method: register