services:
    # Services
    daybreak_studios_airbrake.service.airbrake:
        class: DaybreakStudios\Bundle\AirbrakeBundle\Services\AirbrakeService

    # Listeners
    daybreak_studios_airbrake.listener.exception:
        class: DaybreakStudios\Bundle\AirbrakeBundle\Listener\ExceptionListener
        arguments:
            - '@daybreak_studios_airbrake.service.airbrake'
        tags:
            - name: kernel.event_listener
              event: kernel.exception
              method: onKernelException
            - name: kernel.event_listener
              event: console.exception
              method: onConsoleException

    daybreak_studios_airbrake.listener.shutdown:
        class: DaybreakStudios\Bundle\AirbrakeBundle\Listener\ShutdownListener
        arguments:
            - '@daybreak_studios_airbrake.service.airbrake'
        tags:
            - name: kernel.event_listener
              event: kernel.controller
              method: register